builds:
  - env:
      - CGO_ENABLED=0
      - GOFLAGS = -mod=vendor
      - GO111MODULE = on
    goos:
      - windows
      - linux
      - darwin
    flags:
      - -trimpath
      - -tags=netgo
      - -a
    ldflags:
      - -extldflags "-static"
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName  }}-{{ .Os  }}-{{ .Arch  }}"
checksum:
  name_template: 'CHECKSUMS'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'